pipeline {

    agent none

    stages {

        stage('Checkout') {

            agent any

            steps {
                checkout scm
            }
        }

        stage('Build and Test') {

            agent {
                docker {
                    image 'mirzasadaq/maven-docker-agent:v1'
                    args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }

            steps {

                sh '''
                    cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
                    mvn clean package
                '''
            }
        }

        stage('Static Code Analysis') {

            agent {
                docker {
                    image 'mirzasadaq/maven-docker-agent:v1'
                    args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }

            environment {
                SONAR_URL = "http://54.242.237.224:9000"
            }

            steps {

                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {

                    sh '''
                        cd java-maven-sonar-argocd-helm-k8s/spring-boot-app

                        mvn sonar:sonar \
                        -Dsonar.login=$SONAR_AUTH_TOKEN \
                        -Dsonar.host.url=${SONAR_URL}
                    '''
                }
            }
        }

        stage('Build and Push Docker Image') {

            agent {
                docker {
                    image 'mirzasadaq/maven-docker-agent:v1'
                    args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }

            environment {

                DOCKER_IMAGE = "mirzasadaq/argocd-app:${BUILD_NUMBER}"
            }

            steps {

                script {

                    sh '''
                        cd java-maven-sonar-argocd-helm-k8s/spring-boot-app

                        docker build -t ${DOCKER_IMAGE} .
                    '''

                    def dockerImage = docker.image("${DOCKER_IMAGE}")

                    docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {

                        dockerImage.push()
                    }
                }
            }
        }

        stage('Update Deployment File') {

            agent any

            environment {

                GIT_REPO_NAME = "argocd-practice"
                GIT_USER_NAME = "Mirzasadaq"
            }

            steps {

                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {

                    sh '''
                        git config user.email "mirzasadaq8446@gmail.com"

                        git config user.name "Mirzasadaq"

                        sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml

                        git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml

                        git commit -m "Update deployment image to version ${BUILD_NUMBER}"

                        git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                    '''
                }
            }
        }
    }
}
